# Generated by Django 3.0.1 on 2019-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeshirt',
            name='content_url',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styleshirt',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
