# Generated by Django 3.0.1 on 2019-12-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0002_auto_20191228_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styleshirt',
            name='url',
        ),
        migrations.AddField(
            model_name='styleshirt',
            name='image',
            field=models.FileField(default='', upload_to='styles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styleshirt',
            name='image_ckpt',
            field=models.FileField(default=1, upload_to='styles/'),
            preserve_default=False,
        ),
    ]
