# Generated by Django 3.0.1 on 2020-01-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0003_auto_20191229_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeshirt',
            name='content_url',
        ),
        migrations.AddField(
            model_name='completeshirt',
            name='content',
            field=models.FileField(default=1, upload_to='content/'),
            preserve_default=False,
        ),
    ]
