# Generated by Django 3.0.4 on 2020-04-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=50)),
                ('line_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=10)),
                ('is_shipping', models.BooleanField(default=False)),
                ('is_billing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('discount_percentage', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Undisclosed')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'CustomUsers',
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('image_model', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'styles',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('unit_price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('c', 'Cash on delivery'), ('d', 'Debit Card'), ('p', 'PayTM')], max_length=1)),
                ('payment_status', models.BooleanField()),
                ('ordered_at', models.DateTimeField()),
                ('expected_delivery', models.DateTimeField()),
                ('delivered_at', models.DateTimeField()),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address_set', to='main.Address')),
                ('coupon_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Coupon')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address_set', to='main.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser')),
            ],
            options={
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CompleteDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('content_image', models.URLField()),
                ('result_design', models.URLField()),
                ('styled_templates', models.TextField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Styles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser')),
            ],
            options={
                'verbose_name_plural': 'CompleteDesigns',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_purchased', models.BooleanField()),
                ('styled_template_url', models.URLField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('added_at', models.DateTimeField()),
                ('last_updated_at', models.DateTimeField()),
                ('complete_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CompleteDesign')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Templates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser')),
            ],
            options={
                'verbose_name_plural': 'cart',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser'),
        ),
    ]
