# Generated by Django 3.0.3 on 2020-02-10 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Undisclosed')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('image_model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('unit_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.URLField()),
                ('styled_image', models.URLField()),
                ('bill_amount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('c', 'Cash on delivery'), ('d', 'Debit Card'), ('p', 'PayTM')], max_length=1)),
                ('payment_status', models.BooleanField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Styles')),
                ('templates', models.ManyToManyField(to='main.Templates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser')),
            ],
        ),
    ]
